import { ROLES, STAFF_ROLES } from "./roles";

const statusOptions = (values, defaultLabel = "All") => {
  const options = values.map((value) => ({
    value,
    label: value === "all" ? defaultLabel : value.replace(/-/g, " ").replace(/\b\w/g, (char) => char.toUpperCase()),
  }));
  
  if (!values.includes("all") && defaultLabel !== false) {
    return [{ value: "all", label: defaultLabel }, ...options];
  }
  
  return options;
};

const studentSource = {
  endpoint: "/students",
  valueKey: "id",
  label: (item) => `${item.firstName} ${item.lastName} - ${item.admissionNo}`,
};

const teacherSource = {
  endpoint: "/teachers",
  valueKey: "id",
  label: (item) => `${item.firstName} ${item.lastName} - ${item.employeeId}`,
};

const feeSource = {
  endpoint: "/fees",
  valueKey: "id",
  label: (item) => `${item.student?.firstName} - Session ${item.feeStructure?.sessionId} - ₹${item.totalFee}`,
};

const examSource = {
  endpoint: "/exams",
  valueKey: "id",
  label: (item) => `${item.title} - ${item.subject}`,
};

const vehicleSource = {
  endpoint: "/transport/vehicles",
  valueKey: "id",
  label: (item) => `${item.vehicleNumber} (${item.driverName})`,
};

const routeSource = {
  endpoint: "/transport/routes",
  valueKey: "id",
  label: (item) => item.routeName,
};

const expenseCategorySource = {
  endpoint: "/expenses/categories",
  valueKey: "id",
  label: (item) => item.name,
};

const hostelSource = {
  endpoint: "/hostel/hostels",
  valueKey: "id",
  label: (item) => item.name,
};

const roomSource = {
  endpoint: "/hostel/rooms",
  valueKey: "id",
  label: (item) => `${item.roomNumber} (${item.hostel?.name})`,
};

const inventoryCategorySource = {
  endpoint: "/inventory/categories",
  valueKey: "id",
  label: (item) => item.name,
};

const inventoryItemSource = {
  endpoint: "/inventory/items",
  valueKey: "id",
  label: (item) => `${item.name} (${item.sku || 'N/A'}) - Qty: ${item.quantity}`,
};

export const moduleConfigs = {
  users: {
    key: "users",
    title: "Users",
    description: "Admin-only user directory and access management.",
    endpoint: "/users",
    roles: [ROLES.ADMIN],
    actions: {
      create: [ROLES.ADMIN],
      update: [ROLES.ADMIN],
      delete: [ROLES.ADMIN],
    },
    searchPlaceholder: "Search by name, email, phone, or role",
    filters: [
      {
        name: "role",
        label: "Role",
        options: [
          { value: "all", label: "All" },
          { value: ROLES.ADMIN, label: "Admin" },
          { value: ROLES.TEACHER, label: "Teacher" },
          { value: ROLES.STUDENT, label: "Student" },
          { value: ROLES.PARENT, label: "Parent" },
        ],
      },
      {
        name: "isActive",
        label: "Active",
        options: [
          { value: "all", label: "All" },
          { value: "true", label: "Active" },
          { value: "false", label: "Inactive" },
        ],
      },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "role", label: "Role", badge: true },
      { key: "phone", label: "Phone" },
      { key: "isActive", label: "Active", render: (item) => (item.isActive ? "Yes" : "No") },
      { key: "createdAt", label: "Created", type: "date" },
    ],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "phone", label: "Phone" },
      {
        name: "role",
        label: "Role",
        type: "select",
        required: true,
        options: [
          { value: ROLES.ADMIN, label: "Admin" },
          { value: ROLES.TEACHER, label: "Teacher" },
          { value: ROLES.STUDENT, label: "Student" },
          { value: ROLES.PARENT, label: "Parent" },
        ],
      },
      { name: "password", label: "Password", type: "password", placeholder: "Required for new users" },
      { name: "isActive", label: "Active", type: "checkbox" },
      { name: "avatar", label: "Profile Picture", type: "file" },
    ],
  },
  students: {
    key: "students",
    title: "Student Management",
    description: "Admissions, class rosters, guardians, and student status.",
    endpoint: "/students",
    roles: STAFF_ROLES,
    actions: {
      create: STAFF_ROLES,
      update: STAFF_ROLES,
      delete: [ROLES.ADMIN],
    },
    searchPlaceholder: "Search by admission no, name, class, or parent",
    filters: [
      { name: "status", label: "Status", options: statusOptions(["active", "inactive", "graduated"]) },
      { name: "gender", label: "Gender", options: statusOptions(["male", "female", "other"]) },
    ],
    columns: [
      { key: "admissionNo", label: "Admission No" },
      { key: "student", label: "Student", render: (item) => `${item.firstName} ${item.lastName}` },
      { key: "session", label: "Session" },
      { key: "className", label: "Class" },
      { key: "section", label: "Section" },
      { key: "parentName", label: "Guardian" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "admissionNo", label: "Admission No", required: true },
      { name: "firstName", label: "First Name", required: true },
      { name: "lastName", label: "Last Name", required: true },
      { name: "session", label: "Academic Session", required: true, placeholder: "e.g. 2026-2027" },
      { name: "email", label: "Email", type: "email" },
      { name: "phone", label: "Phone" },
      { name: "className", label: "Class", required: true },
      { name: "section", label: "Section", required: true },
      { name: "rollNumber", label: "Roll Number" },
      {
        name: "gender",
        label: "Gender",
        type: "select",
        required: true,
        options: statusOptions(["male", "female", "other"], "Select gender"),
      },
      { name: "dateOfBirth", label: "Date of Birth", type: "date" },
      { name: "parentName", label: "Guardian Name" },
      { name: "parentPhone", label: "Guardian Phone" },
      { name: "bloodGroup", label: "Blood Group" },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: statusOptions(["active", "inactive", "graduated"], "Select status"),
      },
      { name: "address", label: "Address", type: "textarea" },
      { name: "photo", label: "Student Photo", type: "file" },
    ],
  },
  teachers: {
    key: "teachers",
    title: "Teacher Management",
    description: "Staff profiles, departments, joining dates, and status.",
    endpoint: "/teachers",
    roles: STAFF_ROLES,
    actions: {
      create: [ROLES.ADMIN],
      update: [ROLES.ADMIN],
      delete: [ROLES.ADMIN],
    },
    searchPlaceholder: "Search by employee ID, name, department, or subject",
    filters: [
      { name: "status", label: "Status", options: statusOptions(["active", "inactive", "on-leave"]) },
    ],
    columns: [
      { key: "employeeId", label: "Employee ID" },
      { key: "teacher", label: "Teacher", render: (item) => `${item.firstName} ${item.lastName}` },
      { key: "department", label: "Department" },
      { key: "subject", label: "Subject" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "employeeId", label: "Employee ID", required: true },
      { name: "firstName", label: "First Name", required: true },
      { name: "lastName", label: "Last Name", required: true },
      { name: "email", label: "Email", type: "email" },
      { name: "phone", label: "Phone" },
      { name: "department", label: "Department" },
      { name: "subject", label: "Primary Subject" },
      { name: "qualification", label: "Qualification" },
      { name: "joiningDate", label: "Joining Date", type: "date" },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: statusOptions(["active", "inactive", "on-leave"], "Select status"),
      },
      { name: "address", label: "Address", type: "textarea" },
      { name: "photo", label: "Teacher Photo", type: "file" },
    ],
  },
  attendance: {
    key: "attendance",
    title: "Attendance",
    description: "Daily attendance entries with searchable student history.",
    endpoint: "/attendance",
    roles: STAFF_ROLES,
    actions: {
      create: STAFF_ROLES,
      update: STAFF_ROLES,
      delete: [ROLES.ADMIN],
    },
    searchPlaceholder: "Search by class, section, or remarks",
    filters: [
      { name: "status", label: "Status", options: statusOptions(["present", "absent", "late", "leave"]) },
    ],
    columns: [
      { key: "student", label: "Student", render: (item) => item.student ? `${item.student.firstName} ${item.student.lastName}` : "-" },
      { key: "className", label: "Class" },
      { key: "section", label: "Section" },
      { key: "date", label: "Date", type: "date" },
      { key: "status", label: "Status", badge: true },
      { key: "markedBy.name", label: "Marked By" },
    ],
    fields: [
      { name: "studentId", label: "Student", type: "select", required: true, source: studentSource },
      { name: "className", label: "Class", required: true },
      { name: "section", label: "Section", required: true },
      { name: "date", label: "Date", type: "date", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: statusOptions(["present", "absent", "late", "leave"], "Select status"),
      },
      { name: "remarks", label: "Remarks", type: "textarea" },
    ],
  },
  fees: {
    key: "fees",
    title: "Fees Management",
    description: "Manage fee assignments, due dates, and payment status.",
    endpoint: "/fees",
    roles: STAFF_ROLES,
    actions: {
      create: [ROLES.ADMIN],
      update: [ROLES.ADMIN],
      delete: [ROLES.ADMIN],
    },
    searchPlaceholder: "Search by fee type, term, or notes",
    filters: [
      { name: "status", label: "Status", options: statusOptions(["unpaid", "partial", "paid", "overdue"]) },
    ],
    columns: [
      { key: "student", label: "Student", render: (item) => item.student ? `${item.student.firstName} ${item.student.lastName}` : "-" },
      { key: "sessionId", label: "Session", render: (item) => item.feeStructure?.sessionId || "-" },
      { key: "totalFee", label: "Total Fee", render: (item) => `₹${item.totalFee}` },
      { key: "dueAmount", label: "Due Amount", render: (item) => `₹${item.dueAmount}` },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "studentId", label: "Student", type: "select", required: true, source: studentSource },
      { name: "feeStructureId", label: "Fee Structure ID", required: true },
      { name: "totalFee", label: "Total Fee", type: "number", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: statusOptions(["Due", "Partially Paid", "Paid"], "Select status"),
      },
    ],
  },
  payments: {
    key: "payments",
    title: "Payments",
    description: "Track fee collections, modes, and transaction status.",
    endpoint: "/payments",
    roles: STAFF_ROLES,
    actions: {
      create: [ROLES.ADMIN],
      update: [ROLES.ADMIN],
      delete: [ROLES.ADMIN],
    },
    searchPlaceholder: "Search by transaction ID, method, or status",
    filters: [
      { name: "status", label: "Status", options: statusOptions(["completed", "pending", "failed"]) },
      { name: "method", label: "Method", options: statusOptions(["cash", "card", "bank", "upi", "online"]) },
    ],
    columns: [
      { key: "student", label: "Student", render: (item) => item.studentFee?.student ? `${item.studentFee.student.firstName} ${item.studentFee.student.lastName}` : "-" },
      { key: "fee", label: "Fee Session", render: (item) => item.studentFee?.feeStructure?.sessionId || "Annual Fee" },
      { key: "amount", label: "Amount", render: (item) => `₹${item.amount}` },
      { key: "paymentMethod", label: "Method", render: (item) => <span className="capitalize">{item.paymentMethod}</span> },
      { key: "paymentDate", label: "Payment Date", type: "date" },
      { key: "status", label: "Status", render: () => <span className="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-semibold bg-green-100 text-green-800">Successful</span> },
    ],
    fields: [
      { name: "studentFeeId", label: "Fee Reference", type: "select", required: true, source: feeSource },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "paymentDate", label: "Payment Date", type: "date", required: true },
      {
        name: "paymentMethod",
        label: "Method",
        type: "select",
        required: true,
        options: statusOptions(["cash", "card", "bank", "upi", "online"], "Select method"),
      },
      { name: "receipt", label: "Payment Receipt", type: "file" },
    ],
  },
  exams: {
    key: "exams",
    title: "Exams",
    description: "Plan exams by class, subject, date, and marks structure.",
    endpoint: "/exams",
    roles: STAFF_ROLES,
    actions: {
      create: STAFF_ROLES,
      update: STAFF_ROLES,
      delete: [ROLES.ADMIN],
    },
    searchPlaceholder: "Search by title, subject, class, or description",
    filters: [],
    columns: [
      { key: "title", label: "Title" },
      { key: "subject", label: "Subject" },
      { key: "className", label: "Class" },
      { key: "section", label: "Section" },
      { key: "date", label: "Date", type: "date" },
      { key: "totalMarks", label: "Total Marks" },
    ],
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "subject", label: "Subject", required: true },
      { name: "className", label: "Class", required: true },
      { name: "section", label: "Section", required: true },
      { name: "date", label: "Exam Date", type: "date", required: true },
      { name: "totalMarks", label: "Total Marks", type: "number", required: true },
      { name: "passMarks", label: "Pass Marks", type: "number", required: true },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  results: {
    key: "results",
    title: "Results",
    description: "Publish subject marks and grades against each exam.",
    endpoint: "/results",
    roles: STAFF_ROLES,
    actions: {
      create: STAFF_ROLES,
      update: STAFF_ROLES,
      delete: [ROLES.ADMIN],
    },
    searchPlaceholder: "Search by grade or remarks",
    filters: [
      { name: "grade", label: "Grade", options: statusOptions(["A", "B", "C", "D", "E", "F"]) },
    ],
    columns: [
      { key: "student", label: "Student", render: (item) => item.student ? `${item.student.firstName} ${item.student.lastName}` : "-" },
      { key: "exam.title", label: "Exam" },
      { key: "marksObtained", label: "Marks" },
      { key: "grade", label: "Grade", badge: true },
      { key: "publishedAt", label: "Published", type: "date" },
    ],
    fields: [
      { name: "studentId", label: "Student", type: "select", required: true, source: studentSource },
      { name: "examId", label: "Exam", type: "select", required: true, source: examSource },
      { name: "marksObtained", label: "Marks Obtained", type: "number", required: true },
      { name: "grade", label: "Grade", required: true },
      { name: "remarks", label: "Remarks", type: "textarea" },
      { name: "publishedAt", label: "Published At", type: "date" },
      { name: "reportCard", label: "Report Card PDF", type: "file" },
    ],
  },
  notices: {
    key: "notices",
    title: "Noticeboard",
    description: "School-wide announcements, audience targeting, and pinning.",
    endpoint: "/notices",
    roles: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT, ROLES.PARENT],
    actions: {
      create: STAFF_ROLES,
      update: STAFF_ROLES,
      delete: [ROLES.ADMIN],
    },
    searchPlaceholder: "Search notices by title or message",
    filters: [
      { name: "audience", label: "Audience", options: statusOptions(["all", "students", "teachers", "parents"]) },
    ],
    columns: [
      { key: "title", label: "Title" },
      { key: "audience", label: "Audience", badge: true },
      { key: "publishDate", label: "Publish Date", type: "date" },
      { key: "expiryDate", label: "Expiry Date", type: "date" },
      { key: "isPinned", label: "Pinned", render: (item) => (item.isPinned ? "Yes" : "No") },
    ],
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      {
        name: "audience",
        label: "Audience",
        type: "select",
        required: true,
        options: statusOptions(["all", "students", "teachers", "parents"], "Select audience"),
      },
      { name: "publishDate", label: "Publish Date", type: "date" },
      { name: "expiryDate", label: "Expiry Date", type: "date" },
      { name: "isPinned", label: "Pin to top", type: "checkbox" },
      { name: "attachment", label: "Notice Document", type: "file" },
    ],
  },
  homework: {
    key: "homework",
    title: "Homework",
    description: "Assignments by class, section, subject, and due date.",
    endpoint: "/homework",
    roles: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT],
    actions: {
      create: STAFF_ROLES,
      update: STAFF_ROLES,
      delete: [ROLES.ADMIN],
    },
    searchPlaceholder: "Search by title, class, section, or subject",
    filters: [
      { name: "status", label: "Status", options: statusOptions(["draft", "published", "closed"]) },
    ],
    columns: [
      { key: "title", label: "Title" },
      { key: "subject", label: "Subject" },
      { key: "className", label: "Class" },
      { key: "section", label: "Section" },
      { key: "dueDate", label: "Due Date", type: "date" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "className", label: "Class", required: true },
      { name: "section", label: "Section", required: true },
      { name: "subject", label: "Subject", required: true },
      { name: "dueDate", label: "Due Date", type: "date", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: statusOptions(["draft", "published", "closed"], "Select status"),
      },
      { name: "attachments", label: "Assignment Files", type: "file" },
    ],
  },
  timetable: {
    key: "timetable",
    title: "Timetable",
    description: "Weekly class schedules with JSON-driven period blocks.",
    endpoint: "/timetable",
    roles: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT],
    actions: {
      create: STAFF_ROLES,
      update: STAFF_ROLES,
      delete: [ROLES.ADMIN],
    },
    searchPlaceholder: "Search by class, section, day, or room",
    filters: [
      { name: "day", label: "Day", options: statusOptions(["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]) },
    ],
    columns: [
      { key: "className", label: "Class" },
      { key: "section", label: "Section" },
      { key: "day", label: "Day", badge: true },
      { key: "periods", label: "Periods", render: (item) => `${item.periods?.length || 0} slots` },
    ],
    fields: [
      { name: "className", label: "Class", required: true },
      { name: "section", label: "Section", required: true },
      {
        name: "day",
        label: "Day",
        type: "select",
        required: true,
        options: statusOptions(["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"], "Select day"),
      },
      {
        name: "periods",
        label: "Periods JSON",
        type: "json",
        required: true,
        placeholder:
          "[{\"subject\":\"Math\",\"teacher\":\"teacherId\",\"startTime\":\"09:00\",\"endTime\":\"09:45\",\"room\":\"A1\"}]",
      },
    ],
  },
  library: {
    key: "library",
    title: "Library",
    description: "Book catalogue, availability, category, and shelf tracking.",
    endpoint: "/library",
    roles: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT],
    actions: {
      create: STAFF_ROLES,
      update: STAFF_ROLES,
      delete: [ROLES.ADMIN],
    },
    searchPlaceholder: "Search by title, author, category, ISBN, or shelf",
    filters: [
      { name: "status", label: "Status", options: statusOptions(["available", "limited", "out-of-stock"]) },
    ],
    columns: [
      { key: "catalogueCode", label: "Code" },
      { key: "title", label: "Title" },
      { key: "author", label: "Author" },
      { key: "availableCopies", label: "Available" },
      { key: "quantity", label: "Total" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "catalogueCode", label: "Catalogue Code", required: true },
      { name: "title", label: "Title", required: true },
      { name: "author", label: "Author", required: true },
      { name: "isbn", label: "ISBN" },
      { name: "category", label: "Category" },
      { name: "quantity", label: "Total Quantity", type: "number", required: true },
      { name: "availableCopies", label: "Available Copies", type: "number", required: true },
      { name: "shelf", label: "Shelf" },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: statusOptions(["available", "limited", "out-of-stock"], "Select status"),
      },
      { name: "coverImage", label: "Book Cover", type: "file" },
    ],
  },
  communications: {
    key: "communications",
    title: "Parent Communication",
    description: "Send parent-facing updates across app, email, or SMS channels.",
    endpoint: "/communications",
    roles: STAFF_ROLES,
    actions: {
      create: STAFF_ROLES,
      update: STAFF_ROLES,
      delete: [ROLES.ADMIN],
    },
    searchPlaceholder: "Search by title, message, or parent contact",
    filters: [
      { name: "channel", label: "Channel", options: statusOptions(["app", "email", "sms"]) },
      { name: "status", label: "Status", options: statusOptions(["draft", "sent"]) },
    ],
    columns: [
      { key: "title", label: "Title" },
      { key: "channel", label: "Channel", badge: true },
      { key: "audience", label: "Audience", badge: true },
      { key: "parentName", label: "Parent" },
      { key: "sentAt", label: "Sent At", type: "date" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "message", label: "Message", type: "textarea", required: true },
      {
        name: "channel",
        label: "Channel",
        type: "select",
        required: true,
        options: statusOptions(["app", "email", "sms"], "Select channel"),
      },
      {
        name: "audience",
        label: "Audience",
        type: "select",
        required: true,
        options: statusOptions(["all", "parents", "students", "teachers", "single-parent"], "Select audience"),
      },
      { name: "studentId", label: "Student", type: "select", source: studentSource },
      { name: "parentName", label: "Parent Name" },
      { name: "parentContact", label: "Parent Contact" },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: statusOptions(["draft", "sent"], "Select status"),
      },
      { name: "sentAt", label: "Sent At", type: "date" },
      { name: "attachment", label: "Communication Attachment", type: "file" },
    ],
  },
  enquiries: {
    key: "enquiries",
    title: "Enquiries",
    description: "Manage pre-admission enquiries and leads.",
    endpoint: "/admissions/enquiries",
    roles: STAFF_ROLES,
    actions: { create: STAFF_ROLES, update: STAFF_ROLES, delete: [ROLES.ADMIN] },
    searchPlaceholder: "Search by student name, parent name, phone, or email",
    filters: [
      { name: "status", label: "Status", options: statusOptions(["Pending", "Follow-up", "Closed", "Converted"]) },
    ],
    columns: [
      { key: "studentName", label: "Student Name" },
      { key: "parentName", label: "Parent Name" },
      { key: "phone", label: "Phone" },
      { key: "classApplied", label: "Class" },
      { key: "status", label: "Status", badge: true },
      { key: "createdAt", label: "Date", type: "date" },
    ],
    fields: [
      { name: "studentName", label: "Student Name", required: true },
      { name: "parentName", label: "Parent Name", required: true },
      { name: "phone", label: "Phone", required: true },
      { name: "email", label: "Email", type: "email" },
      { name: "classApplied", label: "Class Applied", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: statusOptions(["Pending", "Follow-up", "Closed", "Converted"], "Select status"),
      },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  applications: {
    key: "applications",
    title: "Admission Applications",
    description: "Manage formal admission applications.",
    endpoint: "/admissions/applications",
    roles: STAFF_ROLES,
    actions: { create: STAFF_ROLES, update: STAFF_ROLES, delete: [ROLES.ADMIN] },
    searchPlaceholder: "Search by name, parent phone, or class",
    filters: [
      { name: "status", label: "Status", options: statusOptions(["Pending", "Under Review", "Approved", "Rejected"]) },
    ],
    columns: [
      { key: "firstName", label: "First Name" },
      { key: "lastName", label: "Last Name" },
      { key: "classApplied", label: "Class" },
      { key: "parentName", label: "Parent" },
      { key: "status", label: "Status", badge: true },
      { key: "appliedAt", label: "Applied", type: "date" },
    ],
    fields: [
      { name: "firstName", label: "First Name", required: true },
      { name: "lastName", label: "Last Name", required: true },
      { name: "dateOfBirth", label: "Date of Birth", type: "date", required: true },
      {
        name: "gender",
        label: "Gender",
        type: "select",
        required: true,
        options: statusOptions(["male", "female", "other"], "Select gender"),
      },
      { name: "parentName", label: "Parent Name", required: true },
      { name: "parentPhone", label: "Parent Phone", required: true },
      { name: "parentEmail", label: "Parent Email", type: "email" },
      { name: "address", label: "Address", type: "textarea" },
      { name: "classApplied", label: "Class Applied", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: statusOptions(["Pending", "Under Review", "Approved", "Rejected"], "Select status"),
      },
      { name: "documents", label: "Upload Documents", type: "file" },
    ],
  },
  "staff-attendance": {
    key: "staff-attendance",
    title: "Staff Attendance",
    description: "Daily attendance entries for teachers and staff.",
    endpoint: "/hr/attendance",
    roles: STAFF_ROLES,
    actions: { create: STAFF_ROLES, update: STAFF_ROLES, delete: [ROLES.ADMIN] },
    searchPlaceholder: "Search by teacher name or remarks",
    filters: [
      { name: "status", label: "Status", options: statusOptions(["Present", "Absent", "Half-Day"]) },
    ],
    columns: [
      { key: "teacher", label: "Teacher", render: (item) => item.teacher ? `${item.teacher.firstName} ${item.teacher.lastName}` : "-" },
      { key: "date", label: "Date", type: "date" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "teacherId", label: "Teacher", type: "select", required: true, source: teacherSource },
      { name: "date", label: "Date", type: "date", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: statusOptions(["Present", "Absent", "Half-Day"], "Select status"),
      },
      { name: "remarks", label: "Remarks", type: "textarea" },
    ],
  },
  "staff-leaves": {
    key: "staff-leaves",
    title: "Staff Leaves",
    description: "Manage teacher leave requests and approvals.",
    endpoint: "/hr/leaves",
    roles: STAFF_ROLES,
    actions: { create: STAFF_ROLES, update: STAFF_ROLES, delete: [ROLES.ADMIN] },
    searchPlaceholder: "Search by teacher name or reason",
    filters: [
      { name: "status", label: "Status", options: statusOptions(["Pending", "Approved", "Rejected"]) },
    ],
    columns: [
      { key: "teacher", label: "Teacher", render: (item) => item.teacher ? `${item.teacher.firstName} ${item.teacher.lastName}` : "-" },
      { key: "startDate", label: "Start Date", type: "date" },
      { key: "endDate", label: "End Date", type: "date" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "teacherId", label: "Teacher", type: "select", required: true, source: teacherSource },
      { name: "startDate", label: "Start Date", type: "date", required: true },
      { name: "endDate", label: "End Date", type: "date", required: true },
      { name: "reason", label: "Reason", type: "textarea", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: statusOptions(["Pending", "Approved", "Rejected"], "Select status"),
      },
      { name: "supportingDoc", label: "Supporting Document", type: "file" },
    ],
  },
  payroll: {
    key: "payroll",
    title: "Payroll",
    description: "Generate and manage salary slips for staff.",
    endpoint: "/hr/payroll",
    roles: [ROLES.ADMIN],
    actions: { create: [ROLES.ADMIN], update: [ROLES.ADMIN], delete: [ROLES.ADMIN] },
    searchPlaceholder: "Search by teacher name",
    filters: [
      { name: "status", label: "Status", options: statusOptions(["Unpaid", "Paid"]) },
    ],
    columns: [
      { key: "teacher", label: "Teacher", render: (item) => item.teacher ? `${item.teacher.firstName} ${item.teacher.lastName}` : "-" },
      { key: "month", label: "Month", render: (item) => `${item.month}/${item.year}` },
      { key: "netSalary", label: "Net Salary", render: (item) => `₹${item.netSalary}` },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "teacherId", label: "Teacher", type: "select", required: true, source: teacherSource },
      { name: "month", label: "Month (1-12)", type: "number", required: true },
      { name: "year", label: "Year", type: "number", required: true },
      { name: "basicSalary", label: "Basic Salary", type: "number", required: true },
      { name: "allowances", label: "Allowances", type: "number" },
      { name: "deductions", label: "Deductions", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: statusOptions(["Unpaid", "Paid"], "Select status"),
      },
      { name: "paymentDate", label: "Payment Date", type: "date" },
      { name: "payslip", label: "Payslip PDF", type: "file" },
    ],
  },
  vehicles: {
    key: "vehicles",
    title: "Vehicles",
    description: "Manage school buses and drivers.",
    endpoint: "/transport/vehicles",
    roles: STAFF_ROLES,
    actions: { create: STAFF_ROLES, update: STAFF_ROLES, delete: [ROLES.ADMIN] },
    searchPlaceholder: "Search by number or driver name",
    filters: [{ name: "status", label: "Status", options: statusOptions(["Active", "Maintenance", "Inactive"]) }],
    columns: [
      { key: "vehicleNumber", label: "Vehicle Number" },
      { key: "driverName", label: "Driver Name" },
      { key: "driverPhone", label: "Driver Phone" },
      { key: "capacity", label: "Capacity" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "vehicleNumber", label: "Vehicle Number", required: true },
      { name: "capacity", label: "Capacity", type: "number", required: true },
      { name: "driverName", label: "Driver Name", required: true },
      { name: "driverPhone", label: "Driver Phone", required: true },
      { name: "status", label: "Status", type: "select", required: true, options: statusOptions(["Active", "Maintenance", "Inactive"], "Select status") },
    ],
  },
  routes: {
    key: "routes",
    title: "Bus Routes",
    description: "Manage transport routes and stops.",
    endpoint: "/transport/routes",
    roles: STAFF_ROLES,
    actions: { create: STAFF_ROLES, update: STAFF_ROLES, delete: [ROLES.ADMIN] },
    searchPlaceholder: "Search by route name",
    filters: [],
    columns: [
      { key: "routeName", label: "Route Name" },
      { key: "vehicle.vehicleNumber", label: "Vehicle" },
    ],
    fields: [
      { name: "routeName", label: "Route Name", required: true },
      { name: "vehicleId", label: "Vehicle", type: "select", required: true, source: vehicleSource },
      { name: "stops", label: "Stops JSON", type: "json", placeholder: "[{\"stop\": \"City Center\", \"fee\": 1000}]" },
    ],
  },
  "transport-allocations": {
    key: "transport-allocations",
    title: "Transport Allocations",
    description: "Assign students to bus routes.",
    endpoint: "/transport/allocations",
    roles: STAFF_ROLES,
    actions: { create: STAFF_ROLES, update: STAFF_ROLES, delete: [ROLES.ADMIN] },
    searchPlaceholder: "Search by student name",
    filters: [],
    columns: [
      { key: "student", label: "Student", render: (item) => item.student ? `${item.student.firstName} ${item.student.lastName}` : "-" },
      { key: "route.routeName", label: "Route" },
      { key: "pickupPoint", label: "Pickup Point" },
      { key: "monthlyFee", label: "Monthly Fee", render: (item) => `₹${item.monthlyFee}` },
    ],
    fields: [
      { name: "studentId", label: "Student", type: "select", required: true, source: studentSource },
      { name: "routeId", label: "Route", type: "select", required: true, source: routeSource },
      { name: "pickupPoint", label: "Pickup Point", required: true },
      { name: "monthlyFee", label: "Monthly Fee", type: "number", required: true },
    ],
  },
  "expense-categories": {
    key: "expense-categories",
    title: "Expense Categories",
    description: "Manage categories for school expenses.",
    endpoint: "/expenses/categories",
    roles: [ROLES.ADMIN],
    actions: { create: [ROLES.ADMIN], update: [], delete: [ROLES.ADMIN] },
    searchPlaceholder: "Search by category name",
    filters: [],
    columns: [
      { key: "name", label: "Category Name" },
      { key: "createdAt", label: "Created At", type: "date" },
    ],
    fields: [
      { name: "name", label: "Category Name", required: true },
    ],
  },
  expenses: {
    key: "expenses",
    title: "Expenses",
    description: "Track and manage school expenditures.",
    endpoint: "/expenses",
    roles: [ROLES.ADMIN],
    actions: { create: [ROLES.ADMIN], update: [], delete: [ROLES.ADMIN] },
    searchPlaceholder: "Search by description",
    filters: [],
    columns: [
      { key: "category.name", label: "Category" },
      { key: "amount", label: "Amount", render: (item) => `₹${item.amount}` },
      { key: "date", label: "Date", type: "date" },
      { key: "description", label: "Description" },
    ],
    fields: [
      { name: "categoryId", label: "Category", type: "select", required: true, source: expenseCategorySource },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "date", label: "Date", type: "date", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "receiptUrl", label: "Receipt Document", type: "file" },
    ],
  },
  hostels: {
    key: "hostels",
    title: "Hostels",
    description: "Manage school hostels and wardens.",
    endpoint: "/hostel/hostels",
    roles: [ROLES.ADMIN],
    actions: { create: [ROLES.ADMIN], update: [ROLES.ADMIN], delete: [ROLES.ADMIN] },
    searchPlaceholder: "Search by hostel name or warden",
    filters: [
      { name: "type", label: "Type", options: statusOptions(["Boys", "Girls", "Co-ed"]) },
    ],
    columns: [
      { key: "name", label: "Hostel Name" },
      { key: "type", label: "Type", badge: true },
      { key: "wardenName", label: "Warden" },
      { key: "wardenContact", label: "Contact" },
    ],
    fields: [
      { name: "name", label: "Hostel Name", required: true },
      {
        name: "type",
        label: "Type",
        type: "select",
        required: true,
        options: statusOptions(["Boys", "Girls", "Co-ed"], "Select type"),
      },
      { name: "wardenName", label: "Warden Name" },
      { name: "wardenContact", label: "Warden Contact" },
      { name: "address", label: "Address", type: "textarea" },
    ],
  },
  "hostel-rooms": {
    key: "hostel-rooms",
    title: "Hostel Rooms",
    description: "Manage rooms within hostels.",
    endpoint: "/hostel/rooms",
    roles: [ROLES.ADMIN],
    actions: { create: [ROLES.ADMIN], update: [ROLES.ADMIN], delete: [ROLES.ADMIN] },
    searchPlaceholder: "Search by room number",
    filters: [
      { name: "type", label: "Type", options: statusOptions(["AC", "Non-AC"]) },
    ],
    columns: [
      { key: "hostel.name", label: "Hostel" },
      { key: "roomNumber", label: "Room Number" },
      { key: "capacity", label: "Capacity" },
      { key: "type", label: "Type", badge: true },
      { key: "costPerBed", label: "Cost Per Bed", render: (item) => `₹${item.costPerBed}` },
    ],
    fields: [
      { name: "hostelId", label: "Hostel", type: "select", required: true, source: hostelSource },
      { name: "roomNumber", label: "Room Number", required: true },
      { name: "capacity", label: "Capacity (Beds)", type: "number", required: true },
      {
        name: "type",
        label: "Type",
        type: "select",
        required: true,
        options: statusOptions(["AC", "Non-AC"], "Select type"),
      },
      { name: "costPerBed", label: "Cost Per Bed", type: "number", required: true },
    ],
  },
  "hostel-allocations": {
    key: "hostel-allocations",
    title: "Hostel Allocations",
    description: "Assign students to hostel rooms.",
    endpoint: "/hostel/allocations",
    roles: [ROLES.ADMIN],
    actions: { create: [ROLES.ADMIN], update: [ROLES.ADMIN], delete: [ROLES.ADMIN] },
    searchPlaceholder: "Search by student name",
    filters: [],
    columns: [
      { key: "student", label: "Student", render: (item) => item.student ? `${item.student.firstName} ${item.student.lastName}` : "-" },
      { key: "room.hostel.name", label: "Hostel" },
      { key: "room.roomNumber", label: "Room" },
      { key: "joinDate", label: "Join Date", type: "date" },
      { key: "leaveDate", label: "Leave Date", type: "date" },
    ],
    fields: [
      { name: "studentId", label: "Student", type: "select", required: true, source: studentSource },
      { name: "roomId", label: "Room", type: "select", required: true, source: roomSource },
      { name: "joinDate", label: "Join Date", type: "date", required: true },
      { name: "leaveDate", label: "Leave Date", type: "date" },
    ],
  },
  "inventory-categories": {
    key: "inventory-categories",
    title: "Inventory Categories",
    description: "Manage categories for school inventory and assets.",
    endpoint: "/inventory/categories",
    roles: [ROLES.ADMIN],
    actions: { create: [ROLES.ADMIN], update: [], delete: [ROLES.ADMIN] },
    searchPlaceholder: "Search by category name",
    filters: [],
    columns: [
      { key: "name", label: "Category Name" },
      { key: "createdAt", label: "Created At", type: "date" },
    ],
    fields: [
      { name: "name", label: "Category Name", required: true },
    ],
  },
  "inventory-items": {
    key: "inventory-items",
    title: "Inventory Items",
    description: "Track uniforms, books, stationery, and assets.",
    endpoint: "/inventory/items",
    roles: [ROLES.ADMIN],
    actions: { create: [ROLES.ADMIN], update: [ROLES.ADMIN], delete: [ROLES.ADMIN] },
    searchPlaceholder: "Search by item name or SKU",
    filters: [
      { name: "status", label: "Status", options: statusOptions(["in-stock", "low-stock", "out-of-stock"]) },
    ],
    columns: [
      { key: "category.name", label: "Category" },
      { key: "name", label: "Item Name" },
      { key: "sku", label: "SKU" },
      { key: "quantity", label: "Quantity" },
      { key: "status", label: "Status", badge: true },
    ],
    fields: [
      { name: "categoryId", label: "Category", type: "select", required: true, source: inventoryCategorySource },
      { name: "name", label: "Item Name", required: true },
      { name: "sku", label: "SKU / Code" },
      { name: "quantity", label: "Initial Quantity", type: "number", required: true },
      { name: "unitPrice", label: "Unit Price", type: "number" },
      { name: "reorderLevel", label: "Reorder Level", type: "number", required: true },
    ],
  },
  "inventory-transactions": {
    key: "inventory-transactions",
    title: "Stock In / Out",
    description: "Log stock additions and distributions.",
    title: "Inventory Transactions",
    endpoint: "/api/inventory/transactions",
    roles: [ROLES.ADMIN],
    columns: [
      { key: "item.name", label: "Item" },
      { key: "type", label: "Type", badge: true },
      { key: "quantity", label: "Quantity" },
      { key: "date", label: "Date", format: "date" },
    ],
    filters: [
      {
        name: "type",
        label: "Transaction Type",
        options: statusOptions(["in", "out"], "All Types"),
      },
    ],
    fields: [
      {
        name: "itemId",
        label: "Item",
        type: "select",
        source: {
          endpoint: "/api/inventory/items",
          valueKey: "id",
          label: (item) => item.name,
        },
        required: true,
      },
      {
        name: "type",
        label: "Type",
        type: "select",
        required: true,
        options: statusOptions(["in", "out"], "Select type"),
      },
      { name: "quantity", label: "Quantity", type: "number", required: true },
      { name: "date", label: "Date", type: "date", required: true },
      { name: "remarks", label: "Remarks", type: "textarea" },
    ],
  },
  roles: {
    key: "roles",
    title: "Roles & Permissions",
    endpoint: "/roles",
    roles: [ROLES.ADMIN],
    columns: [
      { key: "name", label: "Role Name" },
      { key: "description", label: "Description" },
    ],
    fields: [
      { name: "name", label: "Role Name", required: true },
      { name: "description", label: "Description", type: "textarea" },
      {
        name: "permissions",
        label: "Permissions JSON",
        type: "json",
        placeholder: "[\"students.read\", \"fees.write\"]",
      },
    ],
  },
  schools: {
    key: "schools",
    title: "Registered Schools (SaaS)",
    endpoint: "/schools",
    roles: [ROLES.ADMIN],
    columns: [
      { key: "name", label: "School Name" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      { key: "status", label: "Status", badge: true },
      { key: "createdAt", label: "Registered On", type: "date" },
    ],
    fields: [
      { name: "name", label: "School Name", required: true },
      { name: "email", label: "Email", type: "email" },
      { name: "phone", label: "Phone" },
      { name: "address", label: "Address", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: statusOptions(["active", "suspended", "trial"], "Select status"),
      },
      { name: "logo", label: "School Logo", type: "image" },
    ],
  },
};

export const getModuleConfig = (key) => moduleConfigs[key];
export const moduleKeys = Object.keys(moduleConfigs);

export const canAccessModule = (key, role) => {
  const config = getModuleConfig(key);
  return Boolean(config && role && config.roles.includes(role));
};

export const canPerformAction = (config, action, role) =>
  Boolean(role && (config.actions?.[action] || config.roles).includes(role));
