import {
  Bell,
  BookOpen,
  CalendarDays,
  CreditCard,
  FileCheck,
  GraduationCap,
  LayoutDashboard,
  Library,
  Megaphone,
  MessageSquareMore,
  NotebookTabs,
  Receipt,
  UserSquare2,
  Users,
  ClipboardList,
  FileText,
  CalendarClock,
  CalendarRange,
  Banknote,
  Bus,
  Map,
  MapPin,
  Tags,
  Wallet,
  Building,
  BedDouble,
  Key,
  PackageSearch,
  PackageOpen,
  ArrowRightLeft,
} from "lucide-react";
import { ROLES, STAFF_ROLES } from "./roles";

export const navigationItems = [
  {
    href: "/dashboard",
    label: "Dashboard",
    icon: LayoutDashboard,
    roles: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT, ROLES.PARENT],
  },
  {
    href: "/students",
    label: "Students",
    icon: GraduationCap,
    roles: STAFF_ROLES,
  },
  {
    href: "/teachers",
    label: "Teachers",
    icon: UserSquare2,
    roles: STAFF_ROLES,
  },
  {
    href: "/attendance",
    label: "Attendance",
    icon: FileCheck,
    roles: STAFF_ROLES,
  },
  {
    href: "/fees",
    label: "Fees",
    icon: CreditCard,
    roles: STAFF_ROLES,
  },
  {
    href: "/payments",
    label: "Payments",
    icon: Receipt,
    roles: STAFF_ROLES,
  },
  {
    href: "/exams",
    label: "Exams",
    icon: NotebookTabs,
    roles: STAFF_ROLES,
  },
  {
    href: "/results",
    label: "Results",
    icon: BookOpen,
    roles: STAFF_ROLES,
  },
  {
    href: "/notices",
    label: "Noticeboard",
    icon: Bell,
    roles: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT, ROLES.PARENT],
  },
  {
    href: "/homework",
    label: "Homework",
    icon: Megaphone,
    roles: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT],
  },
  {
    href: "/timetable",
    label: "Timetable",
    icon: CalendarDays,
    roles: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT],
  },
  {
    href: "/library",
    label: "Library",
    icon: Library,
    roles: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT],
  },
  {
    href: "/communications",
    label: "Parent Comms",
    icon: MessageSquareMore,
    roles: STAFF_ROLES,
  },
  {
    href: "/users",
    label: "Users",
    icon: Users,
    roles: [ROLES.ADMIN],
  },
  {
    href: "/roles",
    label: "Permissions",
    icon: Key,
    roles: [ROLES.ADMIN],
  },
  {
    href: "/super-admin",
    label: "SaaS Admin",
    icon: Building,
    roles: [ROLES.ADMIN],
  },
  {
    href: "/admissions/enquiries",
    label: "Enquiries",
    icon: ClipboardList,
    roles: STAFF_ROLES,
  },
  {
    href: "/admissions/applications",
    label: "Admissions",
    icon: FileText,
    roles: STAFF_ROLES,
  },
  {
    href: "/hr/attendance",
    label: "Staff Attendance",
    icon: CalendarClock,
    roles: STAFF_ROLES,
  },
  {
    href: "/hr/leaves",
    label: "Staff Leaves",
    icon: CalendarRange,
    roles: STAFF_ROLES,
  },
  {
    href: "/hr/payroll",
    label: "Payroll",
    icon: Banknote,
    roles: [ROLES.ADMIN],
  },
  {
    href: "/transport/vehicles",
    label: "Vehicles",
    icon: Bus,
    roles: STAFF_ROLES,
  },
  {
    href: "/transport/routes",
    label: "Bus Routes",
    icon: Map,
    roles: STAFF_ROLES,
  },
  {
    href: "/transport/allocations",
    label: "Allocations",
    icon: MapPin,
    roles: STAFF_ROLES,
  },
  {
    href: "/expenses/categories",
    label: "Exp. Categories",
    icon: Tags,
    roles: [ROLES.ADMIN],
  },
  {
    href: "/expenses",
    label: "Expenses",
    icon: Wallet,
    roles: [ROLES.ADMIN],
  },
  {
    href: "/hostel/hostels",
    label: "Hostels",
    icon: Building,
    roles: [ROLES.ADMIN],
  },
  {
    href: "/hostel/rooms",
    label: "Hostel Rooms",
    icon: BedDouble,
    roles: [ROLES.ADMIN],
  },
  {
    href: "/hostel/allocations",
    label: "Hostel Allocations",
    icon: Key,
    roles: [ROLES.ADMIN],
  },
  {
    href: "/inventory/categories",
    label: "Inv. Categories",
    icon: PackageSearch,
    roles: [ROLES.ADMIN],
  },
  {
    href: "/inventory/items",
    label: "Inventory Items",
    icon: PackageOpen,
    roles: [ROLES.ADMIN],
  },
  {
    href: "/inventory/transactions",
    label: "Stock Log",
    icon: ArrowRightLeft,
    roles: [ROLES.ADMIN],
  },
];

export const protectedPaths = [
  "/dashboard",
  "/students",
  "/alumni",
  "/teachers",
  "/attendance",
  "/fees",
  "/payments",
  "/exams",
  "/results",
  "/notices",
  "/homework",
  "/timetable",
  "/library",
  "/communications",
  "/users",
  "/roles",
  "/super-admin",
  "/admissions/enquiries",
  "/admissions/applications",
  "/hr/attendance",
  "/hr/leaves",
  "/hr/payroll",
  "/transport/vehicles",
  "/transport/routes",
  "/transport/allocations",
  "/expenses/categories",
  "/expenses",
  "/hostel/hostels",
  "/hostel/rooms",
  "/hostel/allocations",
  "/inventory/categories",
  "/inventory/items",
  "/inventory/transactions",
];
